env:
  browser: true
  commonjs: true
  es2021: true
  "jest/globals": true
extends:
  - airbnb-base
ignorePatterns: ["**/node_modules/*.js"]
parserOptions:
  ecmaVersion: 12
rules:
  no-console: off
plugins:
  - jest
overrides:
  - files:
      - './**/*.test.js'
    rules:
      no-underscore-dangle: off
